version: '3.8'

services:
  donates-time-db:
    image: postgres
    container_name: donates-time-db
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "donates-time_api_development"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      DEVISE_JWT_SECRET_KEY: c979ab39fe5ce829d39eb46c88555055ac5fb38e5d3ee60e1f58df88105eb211ef1c08d4f3f1458af67fd850da993ee635a11ad14932b33564775da98687ae5d
    ports:
      - "5432:5432"
    networks:
      - donates-time-api-network

  donates-time-pgadmin:
    image: dpage/pgadmin4
    container_name: donates-time-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@donates-time.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "15432:80"
    depends_on:
      - donates-time-db
    networks:
      - donates-time-api-network

  donates-time-api:
    image: donates-time-api
    container_name: donates-time-api
    build: .
    environment:
      - DBHOST=donates-time-db
      - DBUSER=postgres
      - DBPASS=password
      - PORT=3001
    volumes:
      - .:/donates-time-api
    ports:
      - "3001:3001"
    depends_on:
      - donates-time-db
    networks:
      - donates-time-api-network

networks:
  donates-time-api-network:
    driver: bridge

volumes:
  postgres:
