version: '3.8'

services:
  donates-time-db:
    image: postgres
    container_name: donates-time-db
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "donates-time_api_development"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - donates-time-api-network

  donates-time-pgadmin:
    image: dpage/pgadmin4
    container_name: donates-time-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@donates-time.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "15432:80"
    depends_on:
      - donates-time-db
    networks:
      - donates-time-api-network

  donates-time-api:
    image: donates-time-api
    container_name: donates-time-api
    build: .
    environment:
      - DBHOST=donates-time-db
      - DBUSER=postgres
      - DBPASS=password
    volumes:
      - .:/donates-time-api
    ports:
      - "3000:3000"
    depends_on:
      - donates-time-db
    networks:
      - donates-time-api-network

networks:
  donates-time-api-network:
    driver: bridge

volumes:
  postgres:
