default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['DBHOST'] || ENV["POSTGRES_HOST"] %>
  port: <%= ENV['DBPORT'] || ENV["POSTGRES_PORT"] %>
  username: <%= ENV['DBUSER'] || ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV['DBPASS'] || ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: donates_time_api_development

test:
  <<: *default
  database: donates_time_test_db

production:
  <<: *default
  database: donates_time_api_production
  username: donates_time_api
  password: <%= ENV["BOOKSICA_API_DATABASE_PASSWORD"] %>
